package Initializer.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.projectplugins.BaseProjectPlugin;
import java.util.List;
import jetbrains.mps.plugins.part.ProjectPluginPart;

public class Initializer_ProjectPlugin extends BaseProjectPlugin {
  public Initializer_ProjectPlugin() {
  }
  public void fillCustomParts(List<ProjectPluginPart> parts) {
    parts.add(new EditorComponentListener_ProjectPluginPart());
  }
}
